AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 128
  Exclude:
    - 'spec/**/*'
